### ISSUE TITLE
Support required and optional params in rune-defs

### ISSUE THREAD

**Issue by bricerising** [sygaldry/sygaldry-core#15]
We need to support optional and required params so that we can do better error handling on misconfigured runes.

For example
```
NpmRune:
  params:
    optional:
      - version
      - args
    required:
      - defintion
      - command
```
